version: '3.5'

services:
  server:
    build: .
    ports:
      - 4300:4300
    links:
      - postgres
      - redis

  postgres:
    image: postgres:11.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=care
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=care

  redis:
    image: redis:5.0.0-alpine
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
  flohmarkt-sync:
    external: true
